# Generated by Django 4.0.4 on 2022-04-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='venues',
            new_name='venue',
        ),
    ]
